identifier = "com.luxonis.whisper"
app_version = "1.0.0"

prepare_container = [
    { type = "RUN", command = "apt-get update" },
    { type = "RUN", command = "apt-get install -y wget python3 python3-pip ffmpeg libglib2.0-0 libgl1-mesa-glx libusb-1.0-0 portaudio19-dev libportaudio2" },
]

prepare_build_container = []

build_steps = ["pip3 install -r /app/requirements.txt --break-system-packages"]

entrypoint = ["bash", "-c", "python3 -u /app/main.py --audio_file /app/assets/audio_files/command_LED_yellow.mp3"]
