identifier = "com.example.whisper"
app_version = "1.0.0"

prepare_container = [
    { type = "RUN", command = "apt-get update" },
    { type = "RUN", command = "apt-get install -y python3-pip ffmpeg libusb-1.0-0 portaudio19-dev libportaudio2" },
    { type = "COPY", source = "requirements.txt", target = "requirements.txt" },
    { type = "RUN", command = "pip3 install -r /app/requirements.txt --break-system-packages" },
]

prepare_build_container = []

build_steps = ["pip3 install -r /app/requirements.txt --break-system-packages"]

depthai_models = { yaml_path = "./depthai_models" }

entrypoint = ["bash", "-c", "python3 -u /app/main.py --audio_file /app/assets/audio_files/command_LED_yellow.mp3"]
