identifier = "com.luxonis.palm_detection"

entrypoint = ["bash", "-c", "python3 /app/main.py"]

prepare_container = [
    { type = "RUN", command = "apt-get update" },
    { type = "RUN", command = "apt-get install -y python3 python3-pip libglib2.0-0 libgl1-mesa-glx wget" },
    { type = "RUN", command = "pip3 install --break-system-packages opencv-python==4.10.0.84 blobconverter==1.4.3 --extra-index-url https://artifacts.luxonis.com/artifactory/luxonis-python-snapshot-local/ depthai==3.0.0a3.dev0+bffea0bb249417152985dc158f641ec2e38b4469 numpy~=2.0 depthai-nodes~=0.0.1"}
]

build_steps = []

prepare_build_container = []