name: Gen3 Experiments Runnability Test

on:
  workflow_dispatch:
    inputs:
      depthai_version:

  # push:
  #   branches:
  #     - gen3

jobs:
  test:
    runs-on: ["self-hosted", "testbed-runner"]

    strategy:
      matrix:
        python-version: [3.12]
        platform: [RVC2] #TODO: add RVC4 platform

    steps:
      - name: Clone HIL Framework
        run: |
          git clone https://oauth2:${{secrets.GITLAB_TOKEN}}@gitlab.luxonis.com/luxonis/hil_lab/hil_framework.git --recursive
                
      - name: Add HIL Tools to Path
        run: |
          cd hil_framework
          echo "$(pwd)/lib_testbed/tools" >> $GITHUB_PATH
          echo "PYTHONPATH="$PYTHONPATH:$(pwd)"" >> $GITHUB_ENV
          echo "HIL_FRAMEWORK_PATH="$(pwd)"" >> $GITHUB_ENV
          
      - name: Run Test
        run: |
          CMD="hil --testbed oak4-pro --reservation-name 'dominik.zacek@luxonis.com' --commands 'cd ~/Documents/source/depthai-experiments' 'git fetch' 'git checkout ${{ github.ref_name }}' 'git pull' 'python3 gen3_script_tester.py --environment-variables DEPTHAI_PLATFORM=${{ matrix.platform }} --virtual-display --path ./neural-networks/advanced-examples/object-detection/mobile-object-localizer"
          if [ -n "${{ github.event.inputs.depthai_version }}" ]; then
            CMD="$CMD --depthai-version ${{ github.event.inputs.depthai_version }}"
          fi
          CMD="$CMD'"
          eval $CMD
        #TODO: swap for hil --revision RVC4 when possible infrastructure-wise
