name: Gen3 Experiments Runnability Test

on:
  workflow_dispatch:
    inputs:
      depthai_version:

  # push:
  #   branches:
  #     - gen3

jobs:
  test:
    runs-on: ["self-hosted", "testbed-runner"]

    strategy:
      matrix:
        python-version: [3.12]
        platform: [RVC2] #TODO: add RVC4 platform

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Add HIL Tools to Path
        run: |
          echo "/home/$USER/hil_framework/lib_testbed/tools" >> $GITHUB_PATH
          echo "PYTHONPATH="$PYTHONPATH:/home/$USER/hil_framework"" >> $GITHUB_ENV
          echo "HIL_FRAMEWORK_PATH="/home/$USER/hil_framework"" >> $GITHUB_ENV
          
      - name: Run Test
        run: |
          export RESERVATION_NAME="https://github.com/$GITHUB_REPOSITORY/actions/$GITHUB_RUN_ID-${{ matrix.python-version }}-${{ matrix.platform }}"
          CMD="hil --testbed oak4-pro --reservation-name $RESERVATION_NAME --wait --sync-workspace --commands 'cd /tmp/depthai-experiments' 'python3 gen3_script_tester.py --environment-variables DEPTHAI_PLATFORM=${{ matrix.platform }} --virtual-display --path ./neural-networks/advanced-examples/object-detection/mobile-object-localizer"
          if [ -n "${{ github.event.inputs.depthai_version }}" ]; then
            CMD="$CMD --depthai-version ${{ github.event.inputs.depthai_version }}"
          fi
          CMD="$CMD'"
          eval $CMD
        #TODO: swap for hil --revision RVC4 when possible infrastructure-wise
